global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: "retro-board-api"
    scrape_interval: 5s  
    metrics_path: /metrics  
    static_configs:
      - targets: ["host.docker.internal:9000"]  

  - job_name: "prometheus"  
    static_configs:
      - targets: ["localhost:9090"]
